# Generated by Django 4.2.7 on 2023-12-06 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_experienceinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienceinfo',
            name='year_of_experience',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='SkillsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
