# Generated by Django 4.2.7 on 2023-12-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_experienceinfo_year_of_experience_skillsinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillsinfo',
            name='profile',
        ),
        migrations.AddField(
            model_name='skillsinfo',
            name='description',
            field=models.CharField(default='Default Description', max_length=100),
        ),
        migrations.AddField(
            model_name='skillsinfo',
            name='name',
            field=models.CharField(default='Default Name', max_length=50),
        ),
    ]
